### ISSUE TITLE
CD-11: Improve the styling/UI of the website

### ISSUE THREAD

**Issue by farnaf** [cse110-fa21-group28/meal-buddy#21]
## Deadline: Saturday (12/04/2021) before midnight (11:59PM)

**MUST** be worked on:
- [x] Add styling elements, choose a theme for the website. We need styling for the following:
    - [x] recipeCards
    - [x] recipeExpand (when recipeCard is clicked)
    - [x] publicRecipeCard (just make sure styling applies to this too)
    - [x] navigation bar
    - [x] login page (index.html)
    - [x] home page + tutorial image ([CD-6](https://github.com/cse110-fa21-group28/meal-buddy/issues/12))
- [x] Make sure the styling is consistent across **ALL** HTML files/pages

**Comment by Ray160** [comment]
The expand page isn't fully finished but the rest is done.

**Comment by Fhuynh1** [comment]
The styling is done, but something went wrong and the recipeExpand shows up on the bottom of the page rather than as a new page.
