### ISSUE TITLE
CD-14: Setup the backend for Recipes page

### ISSUE THREAD

**Issue by farnaf** [cse110-fa21-group28/meal-buddy#32]
## Deadline: Saturday (12/04/2021) before midnight (11:59PM)

In summary, firebase's database should be populated with at **least 20 recipes** that have ALL the required fields (title, image url, calories, description, ingredients, instructions) for a recipe. 

The following are the tasks that **MUST** be worked on:
- [x] add 20 recipes (firebase documents) in public_recipe (firebase collection)
- [x] test and double-check that the function(s) in /public/backend/public_recipe.js work (frontend developers should be able to use these functions inside other JavaScript files, with no errors or odd behavior)

The following are the tasks that **CAN (nice-to-have)** be worked on:
- [ ] add 20 more recipes to the database

**Comment by Derrick2000** [comment]
Initially, we didn't design the category of "instruction", other than that it's all good
